language: python
dist: xenial
matrix:
  include:
    - python: 3.6
    - python: 3.7

services: xvfb
cache: pip

addons:
  apt:
    packages:
    - gfortran
    - libncurses5-dev

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes True --set changeps1 False
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Create conda test environment
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy pandas xarray requests beautifulsoup4 lxml netCDF4 pytest-cov pytest-ordering future
  - conda activate test-environment
  # Delete below once we migrate fully to pip
  - conda install dask portalocker toolz
  # Get latest coveralls from pip, not conda
  - pip install coveralls
  - pip install pytest-flake8
  - pip install portalocker
  # Dependencies not available through conda, install through pip
  - pip install "cdflib<0.3.20"
  # Custom pysat install
  - pip install --index-url https://test.pypi.org/simple/ pysat==3.0.0rc2
  # set up data directory
  - mkdir /home/travis/build/pysatData
  # install pysatNASA
  - python setup.py install

# command to run tests
script:
 - pytest -vs --flake8 --cov=pysatNASA/

after_success:
 - coveralls --rcfile=setup.cfg
